import type { SimulationRun, SimulationSpec } from "./simulation.js";

const escapeHtml = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");

export function generateSimulationReport(spec: SimulationSpec, run: SimulationRun): string {
  const metrics = Object.entries(run.metrics).map(([id, value]) => `<article><small>${escapeHtml(id)}</small><strong>${value.mean.toFixed(2)}</strong><span>p05 ${value.p05.toFixed(2)} · p95 ${value.p95.toFixed(2)}</span></article>`).join("");
  const paths = Object.entries(run.paths).sort((a, b) => b[1] - a[1]).map(([path, count]) => {
    const ids = run.worlds.filter((world) => world.path.join(" → ") === path).map((world) => world.index);
    return `<button type="button" data-label="${escapeHtml(path)}" data-worlds="${ids.join(",")}"><span>${path.split(" → ").map((part) => escapeHtml(part.replace(/^[^:]+:/, ""))).join(" <i>→</i> ")}</span><b>${count}</b><small>${Math.round(count / run.worlds.length * 100)}%</small></button>`;
  }).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Possible worlds</title><style>
  :root{color-scheme:dark;--bg:#171717;--surface:#202020;--ink:#ececec;--muted:#8b8b8b;--line:rgba(255,255,255,.08)}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:13px/1.45 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.shell{max-width:980px;margin:auto;padding:24px}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px}.metrics article,.paths button{border:1px solid var(--line);border-radius:10px;background:var(--surface)}.metrics article{display:grid;padding:12px}.metrics small,.metrics span,.paths small{color:var(--muted);font-size:10px}.metrics strong{font-size:22px}.paths{display:grid;gap:6px;margin-top:18px}.paths button{min-height:48px;display:grid;grid-template-columns:minmax(0,1fr) auto 42px;align-items:center;gap:10px;padding:9px 12px;color:var(--ink);text-align:left;cursor:pointer}.paths button:hover,.paths button:focus-visible{border-color:rgba(255,255,255,.24)}.paths span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.paths i{color:var(--muted);font-style:normal}.paths b{text-align:right}.paths small{text-align:right}@media(max-width:600px){.shell{padding:12px}.paths button{grid-template-columns:minmax(0,1fr) auto}.paths small{display:none}}</style></head><body><main class="shell"><section class="metrics">${metrics}</section><section class="paths">${paths}</section></main><script>document.querySelectorAll('[data-worlds]').forEach(button=>button.onclick=()=>{const worldIds=button.dataset.worlds.split(',').filter(Boolean).map(Number);if(window.parent!==window)window.parent.postMessage({type:'river:selection',kind:'path',label:button.dataset.label,worldIds},location.origin)});</script></body></html>`;
}
