import type { ScenarioModel } from "./domain.js";
import { analyzeScenario, type ScenarioResult } from "./adapters/repeated-game.js";

export interface WorldLabel { short: string; detail: string }
export type WorldLabels = Record<string, WorldLabel>;
export interface WorldLabelNode { id: string; stage: number; key: string; count: number }

interface VisualWorld {
  strategy: string;
  opening: string;
  response: string;
  regime: string;
  winners: readonly string[];
}

const labelMarker = "/*__WORLD_LABELS__*/{}";
const escapeHtml = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const worldPath = (world: VisualWorld) => ["all", world.strategy, world.opening, world.response, world.regime, world.winners.length === 1 ? world.winners[0]! : "Balance"];

function visualWorlds(model: ScenarioModel, result: Pick<ScenarioResult, "trials">): VisualWorld[] {
  const usesTeams = model.players.some((player) => player.team);
  return result.trials.map((trial) => ({
    strategy: Object.entries(trial.digest.strategies).map(([name, strategy]) => `${name}=${strategy}`).join(" · "),
    opening: trial.digest.opening,
    response: trial.digest.response,
    regime: trial.digest.regime,
    winners: usesTeams ? trial.teamWinners : trial.winners,
  }));
}

export function visibleWorldLabelNodes(model: ScenarioModel, result: ScenarioResult): WorldLabelNode[] {
  const paths = visualWorlds(model, result).map(worldPath);
  return Array.from({ length: 6 }, (_, stage) => {
    const counts = new Map<string, number>();
    for (const path of paths) counts.set(path[stage]!, (counts.get(path[stage]!) ?? 0) + 1);
    const ranked = [...counts].sort((a, b) => b[1] - a[1]);
    const keep = new Set(ranked.slice(0, stage === 1 ? 5 : 6).map(([key]) => key));
    const visible = new Map<string, number>();
    for (const [key, count] of ranked) {
      const shown = keep.has(key) ? key : `other:${stage}`;
      visible.set(shown, (visible.get(shown) ?? 0) + count);
    }
    return [...visible].sort((a, b) => b[1] - a[1]).map(([key, count]) => ({ id: `${stage}|${key}`, stage, key, count }));
  }).flat();
}

export function injectWorldLabels(html: string, labels: WorldLabels): string {
  if (!html.includes(labelMarker)) throw new Error("World label marker is missing");
  return html.replace(labelMarker, JSON.stringify(labels).replaceAll("<", "\\u003c"));
}

export function generateWorldsVisual(model: ScenarioModel, trials = 600, seed = 42, ready?: Pick<ScenarioResult, "trials">): string {
  const result = ready ?? analyzeScenario(model, trials, seed);
  const worlds = visualWorlds(model, result);
  const payload = {
    situation: model.situation,
    trials,
    seed,
    worlds,
  };
  const data = JSON.stringify(payload).replaceAll("<", "\\u003c");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>River of possible worlds</title>
<style>
:root{color-scheme:dark;--bg:#171717;--paper:#202020;--ink:#ececec;--muted:#8b8b8b;--rule:rgba(255,255,255,.07);--shadow:rgba(0,0,0,.25)}
*{box-sizing:border-box;scrollbar-width:thin;scrollbar-color:rgba(255,255,255,.16) transparent}*::-webkit-scrollbar{width:8px;height:8px}*::-webkit-scrollbar-track{background:transparent}*::-webkit-scrollbar-thumb{border:2px solid transparent;border-radius:999px;background:rgba(255,255,255,.16);background-clip:padding-box}body{margin:0;min-height:100vh;background:var(--bg);color:var(--ink);font:14px/1.45 ui-sans-serif,-apple-system,BlinkMacSystemFont,"SF Pro Text","Segoe UI",sans-serif;font-variant-numeric:tabular-nums;-webkit-font-smoothing:antialiased}.shell{min-height:100vh;margin:0;padding:22px 18px 0;display:flex;flex-direction:column}.embedded .shell{padding:0}.embedded .shell>header{display:none}.eyebrow{text-transform:uppercase;letter-spacing:.12em;font-size:10px;color:var(--muted);margin-bottom:7px}h1{font:590 clamp(28px,4vw,46px)/1.04 ui-sans-serif,-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",sans-serif;letter-spacing:-.035em;max-width:900px;margin:0;text-wrap:balance}.scenario{max-width:820px;color:var(--muted);font-size:13px;margin-top:11px}.surface{position:relative;flex:1;min-height:0;overflow:hidden}.river-wrap{position:absolute;inset:0;overflow:auto;outline:none;overscroll-behavior:contain;cursor:grab;touch-action:none;user-select:none;-webkit-user-select:none}.river-wrap:focus-visible{box-shadow:inset 0 0 0 1px rgba(255,255,255,.18)}.river-wrap.dragging{cursor:grabbing}.river{display:block;max-width:none;transform-origin:top left}.flow{opacity:.3;cursor:pointer;transition:opacity 180ms ease}.flow:hover,.flow.active{opacity:.72}.flow.dim,.node-group.dim{opacity:.06}.node{stroke:var(--bg);stroke-width:1.5}.node-hit{fill:transparent;cursor:pointer}.node-label{font-size:11px;fill:var(--ink);pointer-events:none}.node-count{font-size:9px;fill:var(--muted);pointer-events:none}.stage-label{font-size:9px;letter-spacing:.11em;text-transform:uppercase;fill:var(--muted)}.node-group{transition:opacity 180ms ease}.flow:focus,.flow:focus-visible,.node-group:focus,.node-group:focus-visible{outline:none;filter:none}.zoom-controls{position:absolute;z-index:3;right:12px;bottom:12px;display:flex;align-items:center;padding:3px;border-radius:10px;background:rgba(32,32,32,.94);box-shadow:0 8px 24px rgba(0,0,0,.28),0 0 0 1px var(--rule)}.zoom-controls button{min-width:34px;height:34px;border:0;border-radius:7px;background:transparent;color:var(--ink);font:500 14px/1 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;cursor:pointer}.zoom-controls button:hover{background:rgba(255,255,255,.07)}.zoom-controls button:focus-visible{outline:2px solid rgba(255,255,255,.3);outline-offset:1px}.zoom-value{width:54px;color:var(--muted);font-size:10px}.zoom-hint{position:absolute;z-index:2;left:12px;bottom:12px;border-radius:8px;background:rgba(32,32,32,.9);padding:7px 10px;color:var(--muted);font-size:10px;pointer-events:none;transition:opacity 200ms ease}.zoom-hint.hidden{opacity:0}
.river-stage{display:grid;place-items:center}.node-label-guard{fill:transparent;cursor:grab}.node-group.active .node{stroke:var(--ink);stroke-width:2.5}.node-label-group.dim{opacity:.06}.node-label-group.active .node-label{fill:#fff;font-weight:650}.node-label-group.active .node-count{fill:#c7c7c7}
@media(max-width:760px){.shell{padding:14px 9px 0}.zoom-controls{right:8px;bottom:8px}.zoom-hint{display:none}}
@media(prefers-reduced-motion:reduce){*{transition:none!important}}
</style></head><body><main class="shell"><header><div class="eyebrow">${trials} possible worlds${model.timeframe ? ` · ${escapeHtml(model.timeframe)}` : ""}</div><h1>River of possible worlds</h1><div class="scenario" id="scenario"></div></header><section class="surface"><div class="river-wrap" id="river-wrap" tabindex="0" aria-label="Zoomable river of possible worlds"><div class="river-stage" id="river-stage"><svg class="river" id="river" role="img" aria-label="River of possible worlds"></svg></div></div><div class="zoom-controls" aria-label="River zoom controls"><button id="zoom-out" type="button" aria-label="Zoom out">−</button><button class="zoom-value" id="zoom-fit" type="button" aria-label="Fit river to window">Fit</button><button id="zoom-in" type="button" aria-label="Zoom in">+</button></div><div class="zoom-hint" id="zoom-hint">Scroll to zoom · drag to move</div></section></main>
<script>
const EMBEDDED=new URLSearchParams(location.search).has('embed');if(EMBEDDED)document.documentElement.classList.add('embedded');const DATA=${data},NARRATIVE_LABELS=/*__WORLD_LABELS__*/{},svgNS='http://www.w3.org/2000/svg',STAGES=['Situation','Approaches','First move','Reaction','Development','Outcome'],COLORS=['#737373','#8175c9','#c87563','#b28c57','#5d9d84','#5f91a5'],CANVAS_W=1440,CANVAS_H=620,COLUMN_GAP=244,svg=document.querySelector('#river'),wrap=document.querySelector('#river-wrap'),stage=document.querySelector('#river-stage'),zoomValue=document.querySelector('#zoom-fit'),zoomHint=document.querySelector('#zoom-hint');svg.setAttribute('viewBox','0 0 '+CANVAS_W+' '+CANVAS_H);
const labels={all:'All possible worlds','mutual-coop':'Act together','mutual-conflict':'Both sides escalate','trust-holds':'Trust holds','repair':'Trust is restored','retaliation':'Retaliation','exploitation':'One side exploits the situation','escalation':'Tension rises','cooperation':'Stable cooperation','oscillation':'Course keeps changing','fragile':'Fragile balance','conflict':'Stable conflict','exit':'Exit the situation'},approaches={provocable:'reciprocates',forgiving:'is ready to forgive',pavlov:'repeats successful decisions',grim:'never returns after a breach',exploitative:'exploits others’ openness',trusting:'starts with trust',gradual:'escalates its response gradually',erratic:'acts unpredictably',prober:'tests boundaries',contrite:'corrects its own mistakes',detective:'studies the reaction first',zd_generous:'concedes for the shared outcome',zd_extort:'pressures the other side',colluder:'supports the agreement',adaptive:'adapts to others',southampton:'coordinates with allies',alld:'always acts in self-interest',allc:'always remains open to cooperation',tf2t:'reacts after repeated breaches',semigrim:'remembers serious breaches',memory2:'considers the last two moves',shaper:'shapes others’ behavior',loner:'prefers to exit',punisher:'creates consequences for breaches'};
const cleanLabel=value=>value.replaceAll('eachother','each other').replaceAll('ahare','a hare').replaceAll('inkind','in kind');
const fallbackLabel=(v,stage)=>labels[v]||(v.startsWith('defects:')?v.slice(8)+' changes course':v.startsWith('other:')?'Other possibilities':stage===1&&v.includes('=')?v.split(' · ').map(x=>{const parts=x.split('=');return parts[0]+' — '+(approaches[parts[1]]||'its own approach')}).join(' · '):v),narrative=(v,stage)=>NARRATIVE_LABELS[stage+'|'+v],label=(v,stage)=>cleanLabel(narrative(v,stage)?.short||fallbackLabel(v,stage)),detail=(v,stage)=>cleanLabel(narrative(v,stage)?.detail||label(v,stage));
const worldWord=count=>count===1?'world':'worlds';
const labelLines=(v,stage)=>{const words=label(v,stage).split(/\\s+/),lines=[];let line='';for(const word of words){const next=line?line+' '+word:word;if(next.length<=24||!line)line=next;else{lines.push(line);line=word}}if(line)lines.push(line);if(lines.length<=3)return lines;const last=lines.slice(2).join(' ');return[lines[0],lines[1],last.length>23?last.slice(0,22).trimEnd()+'…':last]};
const rawPath=w=>['all',w.strategy,w.opening,w.response,w.regime,w.winners.length===1?w.winners[0]:'Balance'];
function rows(){const raw=DATA.worlds.map((world,id)=>({id,path:rawPath(world)})),maps=STAGES.map((_,stage)=>{const counts={};raw.forEach(row=>counts[row.path[stage]]=(counts[row.path[stage]]||0)+1);const keep=new Set(Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,stage===1?5:6).map(x=>x[0]));return value=>keep.has(value)?value:'other:'+stage});return raw.map(row=>({...row,path:row.path.map((value,stage)=>maps[stage](value))}))}
function graph(){const allRows=rows(),nodes=[],byKey=new Map;STAGES.forEach((_,stage)=>{const counts={};allRows.forEach(row=>counts[row.path[stage]]=(counts[row.path[stage]]||0)+1);Object.entries(counts).sort((a,b)=>b[1]-a[1]).forEach(([key,count])=>{const node={stage,key,count,worldIds:allRows.filter(row=>row.path[stage]===key).map(row=>row.id)};nodes.push(node);byKey.set(stage+'|'+key,node)})});const maxNodes=Math.max(...STAGES.map((_,stage)=>nodes.filter(node=>node.stage===stage).length)),nodeGap=50,scale=(CANVAS_H-70-(maxNodes-1)*nodeGap)/Math.max(1,DATA.worlds.length);STAGES.forEach((_,stage)=>{let y=38;nodes.filter(node=>node.stage===stage).forEach(node=>{node.x=18+stage*COLUMN_GAP;node.y=y;node.h=node.count*scale;y+=node.h+nodeGap})});const map=new Map;allRows.forEach(row=>{for(let stage=0;stage<STAGES.length-1;stage++){const key=stage+'|'+row.path[stage]+'|'+row.path[stage+1],link=map.get(key)||{stage,source:byKey.get(stage+'|'+row.path[stage]),target:byKey.get((stage+1)+'|'+row.path[stage+1]),count:0,worldIds:[]};link.count++;link.worldIds.push(row.id);map.set(key,link)}});const links=[...map.values()],sourceOffset=new Map,targetOffset=new Map;links.sort((a,b)=>a.source.y-b.source.y||a.target.y-b.target.y).forEach(link=>{link.sy=sourceOffset.get(link.source)||0;sourceOffset.set(link.source,link.sy+link.count*scale)});links.sort((a,b)=>a.target.y-b.target.y||a.source.y-b.source.y).forEach(link=>{link.ty=targetOffset.get(link.target)||0;targetOffset.set(link.target,link.ty+link.count*scale)});return{nodes,links,scale}}
const state=graph();function flowPath(link){const x1=link.source.x+22,x2=link.target.x,mid=(x1+x2)/2,y1=link.source.y+link.sy,y2=link.target.y+link.ty,h=link.count*state.scale;return'M'+x1+','+y1+' C'+mid+','+y1+' '+mid+','+y2+' '+x2+','+y2+' L'+x2+','+(y2+h)+' C'+mid+','+(y2+h)+' '+mid+','+(y1+h)+' '+x1+','+(y1+h)+' Z'}
function highlight(ids,active){const selected=new Set(ids);document.querySelectorAll('.flow').forEach((path,index)=>{path.classList.toggle('dim',!state.links[index].worldIds.some(id=>selected.has(id)));path.classList.toggle('active',path===active)});document.querySelectorAll('.node-group').forEach((group,index)=>{const dim=!state.nodes[index].worldIds.some(id=>selected.has(id)),selectedNode=group===active;group.classList.toggle('dim',dim);group.classList.toggle('active',selectedNode);group.labelGroup.classList.toggle('dim',dim);group.labelGroup.classList.toggle('active',selectedNode)})}
function emitSelection(kind,text,worldIds){if(EMBEDDED&&window.parent!==window)window.parent.postMessage({type:'river:selection',kind,label:text,worldIds},location.origin)}
STAGES.forEach((name,index)=>{const text=document.createElementNS(svgNS,'text');text.setAttribute('x',String(18+index*COLUMN_GAP));text.setAttribute('y','16');text.setAttribute('class','stage-label');text.textContent=name;svg.append(text)});
state.links.forEach(link=>{const path=document.createElementNS(svgNS,'path'),title=document.createElementNS(svgNS,'title'),text=label(link.source.key,link.source.stage)+' → '+label(link.target.key,link.target.stage);path.setAttribute('d',flowPath(link));path.setAttribute('fill',COLORS[link.stage+1]);path.setAttribute('class','flow');path.setAttribute('tabindex','0');path.setAttribute('role','button');title.textContent=text+' · '+link.count+' '+worldWord(link.count);path.setAttribute('aria-label',title.textContent);path.append(title);path.onclick=event=>{event.stopPropagation();highlight(link.worldIds,path);emitSelection('flow',text,link.worldIds)};path.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();path.onclick(event)}};svg.append(path)});
state.nodes.forEach(node=>{const lines=labelLines(node.key,node.stage),height=lines.length*12+14,desired=node.y+Math.min(node.h,24)/2-height/2;node.lines=lines;node.labelY=Math.max(26,Math.min(desired,CANVAS_H-height-8));node.labelH=height});
const labelLayer=document.createElementNS(svgNS,'g');labelLayer.setAttribute('class','node-labels');state.nodes.forEach(node=>{const group=document.createElementNS(svgNS,'g'),rect=document.createElementNS(svgNS,'rect'),barHit=document.createElementNS(svgNS,'rect'),labelGroup=document.createElementNS(svgNS,'g'),labelGuard=document.createElementNS(svgNS,'rect'),text=document.createElementNS(svgNS,'text'),count=document.createElementNS(svgNS,'text'),title=document.createElementNS(svgNS,'title'),textX=node.x+30;group.setAttribute('class','node-group');group.setAttribute('tabindex','0');group.setAttribute('role','button');labelGroup.setAttribute('class','node-label-group');for(const [element,x,y,width,height,className] of [[rect,node.x,node.y,22,Math.max(2,node.h),'node'],[barHit,node.x-5,node.y-5,32,Math.max(18,node.h+10),'node-hit'],[labelGuard,node.x+24,node.labelY-5,176,Math.max(32,node.labelH+8),'node-label-guard']]){element.setAttribute('x',String(x));element.setAttribute('y',String(y));element.setAttribute('width',String(width));element.setAttribute('height',String(height));element.setAttribute('class',className)}rect.setAttribute('rx','4');rect.setAttribute('fill',COLORS[node.stage]);labelGuard.onclick=event=>event.stopPropagation();text.setAttribute('class','node-label');node.lines.forEach((line,index)=>{const span=document.createElementNS(svgNS,'tspan');span.setAttribute('x',String(textX));span.setAttribute('y',String(node.labelY+14+index*12));span.textContent=line;text.append(span)});count.setAttribute('x',String(textX));count.setAttribute('y',String(node.labelY+15+node.lines.length*12));count.setAttribute('class','node-count');count.textContent=node.count+' · '+Math.round(node.count/DATA.worlds.length*100)+'%';title.textContent=detail(node.key,node.stage)+' · '+node.count+' '+worldWord(node.count);group.setAttribute('aria-label',title.textContent);group.onclick=event=>{event.stopPropagation();highlight(node.worldIds,group);emitSelection('node',label(node.key,node.stage),node.worldIds)};group.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();group.onclick(event)}};group.append(rect,barHit,title);labelGroup.append(labelGuard,text,count);group.labelGroup=labelGroup;svg.append(group);labelLayer.append(labelGroup)});svg.append(labelLayer);
svg.onclick=()=>{const ids=DATA.worlds.map((_,index)=>index);highlight(ids,null);emitSelection('all','Entire river',ids)};document.querySelector('#scenario').textContent=DATA.situation;
let zoom=1,hintTimer=0,drag=null,moved=false;const fitZoom=()=>Math.min(1,(wrap.clientWidth-2)/CANVAS_W,(wrap.clientHeight-2)/CANVAS_H),hideHint=()=>{clearTimeout(hintTimer);zoomHint.classList.add('hidden')};function layout(){const width=CANVAS_W*zoom,height=CANVAS_H*zoom;svg.style.width=width+'px';svg.style.height=height+'px';stage.style.width=width+wrap.clientWidth+'px';stage.style.height=height+wrap.clientHeight+'px'}function setZoom(next,clientX,clientY){const previous=zoom,rect=wrap.getBoundingClientRect(),x=clientX===undefined?wrap.clientWidth/2:clientX-rect.left,y=clientY===undefined?wrap.clientHeight/2:clientY-rect.top,worldX=(wrap.scrollLeft+x-wrap.clientWidth/2)/previous,worldY=(wrap.scrollTop+y-wrap.clientHeight/2)/previous;zoom=Math.max(.35,Math.min(2.5,next));layout();zoomValue.textContent=Math.round(zoom*100)+'%';wrap.scrollLeft=wrap.clientWidth/2+worldX*zoom-x;wrap.scrollTop=wrap.clientHeight/2+worldY*zoom-y;hideHint()}function fit(){zoom=fitZoom();layout();zoomValue.textContent=Math.round(zoom*100)+'%';wrap.scrollTo({left:CANVAS_W*zoom/2,top:CANVAS_H*zoom/2})}document.querySelector('#zoom-in').onclick=()=>setZoom(zoom*1.2);document.querySelector('#zoom-out').onclick=()=>setZoom(zoom/1.2);zoomValue.onclick=fit;wrap.addEventListener('wheel',event=>{event.preventDefault();setZoom(zoom*Math.exp(-event.deltaY*.0015),event.clientX,event.clientY)},{passive:false});wrap.addEventListener('pointerdown',event=>{if(event.button!==0)return;drag={x:event.clientX,y:event.clientY,left:wrap.scrollLeft,top:wrap.scrollTop,pointerId:event.pointerId,captured:false};moved=false});wrap.addEventListener('pointermove',event=>{if(!drag)return;const dx=event.clientX-drag.x,dy=event.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>4){if(!drag.captured){wrap.setPointerCapture(drag.pointerId);drag.captured=true}moved=true;wrap.classList.add('dragging');wrap.scrollLeft=drag.left-dx;wrap.scrollTop=drag.top-dy}});wrap.addEventListener('pointerup',()=>{drag=null;wrap.classList.remove('dragging')});wrap.addEventListener('click',event=>{if(moved){event.preventDefault();event.stopPropagation();moved=false}},true);window.addEventListener('resize',()=>{if(zoom<=fitZoom()+.02)fit();else layout()});fit();hintTimer=setTimeout(hideHint,4500);
</script></body></html>`;
}
